# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
# t.string "title"
# t.integer "location_id"
# t.integer "user_id"
# t.string "content"

Post.create(title: 'first post', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pharetra nibh sit amet nulla vehicula sollicitudin eu a purus. In eu aliquet nisi. Nulla facilisi. Praesent tincidunt tellus felis, a porta neque molestie et. Duis semper, elit sed elementum rhoncus, sapien metus tincidunt felis, a accumsan nulla tortor vel risus. Morbi vehicula eleifend augue, ac eleifend metus aliquet et. Nulla volutpat nunc non dui egestas cursus. Maecenas sed dolor vulputate, rhoncus eros ut, auctor est. Phasellus ultrices nulla a commodo blandit. Proin dapibus lacinia nisi a consequat. In hac habitasse platea dictumst. Duis luctus nisl ac tortor maximus rutrum.')
Post.create(title: 'second post', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pharetra nibh sit amet nulla vehicula sollicitudin eu a purus. In eu aliquet nisi. Nulla facilisi. Praesent tincidunt tellus felis, a porta neque molestie et. Duis semper, elit sed elementum rhoncus, sapien metus tincidunt felis, a accumsan nulla tortor vel risus. Morbi vehicula eleifend augue, ac eleifend metus aliquet et. Nulla volutpat nunc non dui egestas cursus. Maecenas sed dolor vulputate, rhoncus eros ut, auctor est. Phasellus ultrices nulla a commodo blandit. Proin dapibus lacinia nisi a consequat. In hac habitasse platea dictumst. Duis luctus nisl ac tortor maximus rutrum.')
Post.create(title: 'new post', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pharetra nibh sit amet nulla vehicula sollicitudin eu a purus. In eu aliquet nisi. Nulla facilisi. Praesent tincidunt tellus felis, a porta neque molestie et. Duis semper, elit sed elementum rhoncus, sapien metus tincidunt felis, a accumsan nulla tortor vel risus. Morbi vehicula eleifend augue, ac eleifend metus aliquet et. Nulla volutpat nunc non dui egestas cursus. Maecenas sed dolor vulputate, rhoncus eros ut, auctor est. Phasellus ultrices nulla a commodo blandit. Proin dapibus lacinia nisi a consequat. In hac habitasse platea dictumst. Duis luctus nisl ac tortor maximus rutrum.')
Post.create(title: 'bunk post', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pharetra nibh sit amet nulla vehicula sollicitudin eu a purus. In eu aliquet nisi. Nulla facilisi. Praesent tincidunt tellus felis, a porta neque molestie et. Duis semper, elit sed elementum rhoncus, sapien metus tincidunt felis, a accumsan nulla tortor vel risus. Morbi vehicula eleifend augue, ac eleifend metus aliquet et. Nulla volutpat nunc non dui egestas cursus. Maecenas sed dolor vulputate, rhoncus eros ut, auctor est. Phasellus ultrices nulla a commodo blandit. Proin dapibus lacinia nisi a consequat. In hac habitasse platea dictumst. Duis luctus nisl ac tortor maximus rutrum.')
Post.create(title: 'test post', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pharetra nibh sit amet nulla vehicula sollicitudin eu a purus. In eu aliquet nisi. Nulla facilisi. Praesent tincidunt tellus felis, a porta neque molestie et. Duis semper, elit sed elementum rhoncus, sapien metus tincidunt felis, a accumsan nulla tortor vel risus. Morbi vehicula eleifend augue, ac eleifend metus aliquet et. Nulla volutpat nunc non dui egestas cursus. Maecenas sed dolor vulputate, rhoncus eros ut, auctor est. Phasellus ultrices nulla a commodo blandit. Proin dapibus lacinia nisi a consequat. In hac habitasse platea dictumst. Duis luctus nisl ac tortor maximus rutrum.')
Post.create(title: 'another test post', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pharetra nibh sit amet nulla vehicula sollicitudin eu a purus. In eu aliquet nisi. Nulla facilisi. Praesent tincidunt tellus felis, a porta neque molestie et. Duis semper, elit sed elementum rhoncus, sapien metus tincidunt felis, a accumsan nulla tortor vel risus. Morbi vehicula eleifend augue, ac eleifend metus aliquet et. Nulla volutpat nunc non dui egestas cursus. Maecenas sed dolor vulputate, rhoncus eros ut, auctor est. Phasellus ultrices nulla a commodo blandit. Proin dapibus lacinia nisi a consequat. In hac habitasse platea dictumst. Duis luctus nisl ac tortor maximus rutrum.')
Post.create(title: 'another random post', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pharetra nibh sit amet nulla vehicula sollicitudin eu a purus. In eu aliquet nisi. Nulla facilisi. Praesent tincidunt tellus felis, a porta neque molestie et. Duis semper, elit sed elementum rhoncus, sapien metus tincidunt felis, a accumsan nulla tortor vel risus. Morbi vehicula eleifend augue, ac eleifend metus aliquet et. Nulla volutpat nunc non dui egestas cursus. Maecenas sed dolor vulputate, rhoncus eros ut, auctor est. Phasellus ultrices nulla a commodo blandit. Proin dapibus lacinia nisi a consequat. In hac habitasse platea dictumst. Duis luctus nisl ac tortor maximus rutrum.')
Post.create(title: 'random post', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pharetra nibh sit amet nulla vehicula sollicitudin eu a purus. In eu aliquet nisi. Nulla facilisi. Praesent tincidunt tellus felis, a porta neque molestie et. Duis semper, elit sed elementum rhoncus, sapien metus tincidunt felis, a accumsan nulla tortor vel risus. Morbi vehicula eleifend augue, ac eleifend metus aliquet et. Nulla volutpat nunc non dui egestas cursus. Maecenas sed dolor vulputate, rhoncus eros ut, auctor est. Phasellus ultrices nulla a commodo blandit. Proin dapibus lacinia nisi a consequat. In hac habitasse platea dictumst. Duis luctus nisl ac tortor maximus rutrum.')
Post.create(title: 'last post', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pharetra nibh sit amet nulla vehicula sollicitudin eu a purus. In eu aliquet nisi. Nulla facilisi. Praesent tincidunt tellus felis, a porta neque molestie et. Duis semper, elit sed elementum rhoncus, sapien metus tincidunt felis, a accumsan nulla tortor vel risus. Morbi vehicula eleifend augue, ac eleifend metus aliquet et. Nulla volutpat nunc non dui egestas cursus. Maecenas sed dolor vulputate, rhoncus eros ut, auctor est. Phasellus ultrices nulla a commodo blandit. Proin dapibus lacinia nisi a consequat. In hac habitasse platea dictumst. Duis luctus nisl ac tortor maximus rutrum.')
